routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




// admin



Auth::routes();

Route::get('/', 'HomeController@index')->name('beranda');
Route::get('product', 'ProductUserController@tampil')->name('index');
Route::get('product/{id}', 'ProductUserController@tampilcat')->name('bycat');
Route::get('/product-detail/{slug}', 'DetailController@detail')->name('detail');
Route::get('product/checkout/{slug}', 'CheckoutController@checkout')->name('checkout');
Route::post('product/cari','ProductUserController@carinama')->name('carinama');
Route::post('checkout/berhasil', 'CheckoutController@bayar')->name('bayar');
Route::get('history-transaksi', 'HistoryController@history')->name('history');
Route::get('forgot','ForgotController@index')->name('forgot');
Route::get('forgot-password','ForgotController@cekemail')->name('cekemail');
Route::post('new-password','ForgotController@ubahpassword')->name('ubahpassword');



Route::prefix('seller')
    ->middleware(['auth','seller'])
    ->group(function(){
        Route::resource('category','CategoryController');
        Route::resource('product','ProductController');
        Route::resource('transaksi','TransaksiController');
        Route::get('report','ReportController@lihatlaporan')->name('lihatlaporan');
        Route::get('report/harian','ReportController@laporanfilter')->name('laporanhari');
        Route::get('report/{bulan}','ReportController@laporanbulan')->name('laporanbulan');
        Route::get('/','DashboardController@penghasilan')->name('dashboard');
    });

resources/views/seller/page/category.blade.php
@extends('seller.layouts.app')

@section('title','Kelola Kategori')

@section('content')

<div class="animated fadeIn">
    <div class="row">
    	<h4>Kelola Kategori</h4>
    	<hr>
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong class="card-title"><a href="" class="btn btn-sm btn-primary text-light" data-toggle="modal" data-target="#tambah"><i class="fa fa-plus"></i> Tambah Kategori</a></strong>
                </div>
                <div class="card-body">
                    <table id="bootstrap-data-table" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                            	<th>No</th>
                                <th>Nama Kategori</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                          @foreach($kategori as $items)
                            <tr>
                            	<td>{{$loop->iteration}}</td>
                                <td>{{$items->nama_category}}</td>
                                <td>
                                  <form action="{{route('category.destroy',$items->id)}}" method="post">
                                    @csrf
                                    @method('delete')
                                	<button class="btn btn-sm btn-warning" type="submit"><i class="fa fa-trash"></i> Hapus</button>
                                  </form>
                                </td>
                            </tr>
                           @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>


    </div>
</div>

@endsection

<!-- Modal Tambah-->
<div class="modal fade" id="tambah" tabindex="-1" role="dialog" aria-labelledby="tambahLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="tambahLabel">Tambah Kategori</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="{{route('category.store')}}" method="post">
        @csrf
      <div class="modal-body">
        <label>Nama Kategori</label>
        <div class="form-group">
        	<input type="text" class="form-control" placeholder="nama Kategori" name="catname">
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">batal</button>
        <button type="submit" class="btn btn-primary">Tambah</button>
      </div>
      </form>
    </div>
  </div>
</div>

@push('addon-script')

    <script type="text/javascript">
        $(document).ready(function() {
          $('#bootstrap-data-table-export').DataTable();
      } );
  </script>

@endpush

resources/views/seller/page/dashboard.blade.php
@extends('seller.layouts.app')

@section('title','Dashboard')

@section('content')

        <div class="content">
                @if(Session::has('alert-success'))
                <div class="alert alert-success">
                    <strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
                </div>
                @endif
            <!-- Animated -->
            <div class="animated fadeIn">
                <!-- Widgets  -->
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <div class="card">
                            <div class="card-body">
                                <div class="stat-widget-five">
                                    <div class="stat-icon dib flat-color-1">
                                        <i class="pe-7s-cash"></i>
                                    </div>
                                    <div class="stat-content">
                                        <div class="text-left dib">
                                            <div class="stat-text">Rp. <span class="count">{{$hasil}}</span></div>
                                            <div class="stat-heading">Penghasilan</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-6 col-md-6">
                        <div class="card">
                            <div class="card-body">
                                <div class="stat-widget-five">
                                    <div class="stat-icon dib flat-color-2">
                                        <i class="pe-7s-cart"></i>
                                    </div>
                                    <div class="stat-content">
                                        <div class="text-left dib">
                                            <div class="stat-text"><span class="count">{{$jual}}</span></div>
                                            <div class="stat-heading">Penjualan</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /Widgets -->
                <!--  /Traffic -->
                <div class="clearfix"></div>
                <!-- Orders -->
                <div class="orders">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="box-title">Transaksi Terakhir </h4>
                                </div>
                                <div class="card-body--">
                                    <div class="table-stats order-table ov-h">
                                        <table class="table ">
                                            <thead>
                                                <tr>
                                                    <th class="serial">#</th>
                                                    <th>Invoice</th>
                                                    <th>Nama Penerima</th>
                                                    <th>Tanggal</th>
                                                    <th>Produk</th>
                                                    <th>Qty</th>
                                                    <th>Total</th>
                                                    <th>Status</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach($trans as $items)
                                                <tr>
                                                    <td class="serial">{{$loop->iteration}}</td>
                                                    <td> {{$items->invoice}} </td>
                                                    <td>  <span class="name"> {{$items->nama_penerima}} </span> </td>
                                                    <td> {{$items->created_at}} </td>
                                                    <td> <span class="product"> {{$items->nama_produk}} </span> </td>
                                                    <td><span class="count">{{$items->qty}}</span></td>
                                                    <td>Rp. {{$items->total}}</td>
                                                    <td>
                                                        @if($items->status == 0)
                                                            <p class="badge badge-warning">Menunggu</p>
                                                        @elseif($items->status == 1)
                                                            <p class="badge badge-info">Diproses</p>
                                                        @elseif($items->status == 2 )
                                                            <p class="badge badge-secondary">Dikirim</p>
                                                        @elseif($items->status == 3)
                                                            <p class="badge badge-success">Selesai</p>
                                                        @else
                                                            <p class="badge badge-danger">Batal</p>
                                                        @endif
                                                    </td>
                                                </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </div> <!-- /.table-stats -->
                                </div>
                            </div> <!-- /.card -->
                        </div>  <!-- /.col-lg-8 -->
                    </div>
                </div>
                <!-- /.orders -->
            <!-- /#add-category -->
            </div>
            <!-- .animated -->
        </div>

@endsection

resources/views/seller/page/editproduk.blade.php
@extends('seller.layouts.app')

@section('title','Kelola Produk')

@section('content')


@push('addon-style')
<style>
  .file {
  visibility: hidden;
  position: absolute;
}
</style>

<div class="animated fadeIn">
    <div class="row">
    	<h4>Edit Produk</h4>
    	<hr>
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                   
                </div>
                <form action="{{route('product.update',$data->id)}}" method="post" enctype="multipart/form-data">
                  @csrf
                  @method('put')
                <div class="card-body">
                   <label>Kategori</label>
                  <div class="form-group">
                    <select class="form-control" name="catid">
                      <option> Pilih Kategori </option>
                      @foreach($kategori as $kat)
                      <option value="{{$kat->id}}" @if($data->category_id == $kat->id) selected @endif>{{$kat->nama_category}}</option>
                      @endforeach
                    </select>
                  </div>
                  <label>Nama Produk</label>
                  <div class="form-group">
                    <input type="text" class="form-control" placeholder="nama Produk" name="namaproduk" value="{{$data->nama_produk}}">
                  </div>
                  <label>Deskripsi</label>
                  <div class="form-group">
                    <input type="text" class="form-control" placeholder="Deskripsi Produk" name="deskproduk" value="{{$data->deskripsi}}">
                  </div>
                  <label>Harga Produk</label>
                  <div class="form-group">
                    <input type="text" class="form-control" placeholder="Rp. ......." name="hargaproduk" value="{{$data->harga}}">
                  </div>
                  <label>Stok</label>
                  <div class="form-group">
                    <input type="text" class="form-control" placeholder="Jumlah Stok" name="stok" value="{{$data->stok}}">
                  </div>
                  <div class="form-group">
                  <img style="max-width: 80px;" src="{{asset('/')}}{{$data->foto}}" id="preview" class="img-thumbnail">
                  </div>
                <div class="form-group">
                  <div id="msg"></div>
                    <input type="file" name="fotproduk" class="file" accept="image/*">
                    <div class="input-group my-3">
                      <input type="text" class="form-control" disabled placeholder="Upload File" id="file">
                      <div class="input-group-append">
                        <button type="button" class="browse btn btn-secondary">Browse...</button>
                      </div>
                    </div>
                </div>
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-secondary float-right"> Simpan</button>
                </div>
                </form>
            </div>
        </div>


    </div>
</div>

@endsection

@push('addon-script')
<script>
// Add the following code if you want the name of the file appear on select
$(".custom-file-input").on("change", function() {
  var fileName = $(this).val().split("\\").pop();
  $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});
</script>

<script>
  $(document).on("click", ".browse", function() {
  var file = $(this).parents().find(".file");
  file.trigger("click");
});
$('input[type="file"]').change(function(e) {
  var fileName = e.target.files[0].name;
  $("#file").val(fileName);

  var reader = new FileReader();
  reader.onload = function(e) {
    // get loaded data and render thumbnail.
    document.getElementById("preview").src = e.target.result;
  };
  // read the image file as a data URL.
  reader.readAsDataURL(this.files[0]);
});
</script>
@endpush

resources/views/seller/page/product.blade.php
@extends('seller.layouts.app')

@section('title','Kelola Produk')

@section('content')

<div class="animated fadeIn">
    <div class="row">
    	<h4>Kelola Produk</h4>
    	<hr>
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong class="card-title"><a href="" class="btn btn-sm btn-primary" data-toggle="modal" data-target="#tambah"><i class="fa fa-plus"></i> Tambah barang</a></strong>
                </div>
                <div class="card-body">
                    <table id="bootstrap-data-table" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                            	<th>No</th>
                                <th>Kategori</th>
                                <th>Nama Produk</th>
                                <th>Deskripsi</th>
                                <th>Harga</th>
                                <th>Stok</th>
                                <th>Gambar Produk</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                          @foreach( $product as $items)
                            <tr>
                            	<td>{{$loop->iteration}}</td>
                              <td>{{$items->nama_category}}</td>
                                <td>{{$items->nama_produk}}</td>
                                <td>{{$items->deskripsi}}</td>
                                <td>{{$items->harga}}</td>
                                <td>{{$items->stok}}</td>
                                <td><img style="max-width: 120px;" src="{{asset('/')}}{{$items->foto}}"></td>
                                <td>
                                	<a href="{{route('product.edit',$items->id)}}" class="btn btn-sm btn-secondary"><i class="fa fa-edit"></i></a>

                                  <form action="{{route('product.destroy',$items->id)}}" method="post">
                                    @csrf
                                    @method('delete')
                                	<button type="submit" class="btn btn-sm btn-warning"><i class="fa fa-trash"></i></button>
                                  </form>
                                </td>
                            </tr>
                           @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>


    </div>
</div>

@endsection

<!-- Modal Tambah-->
<div class="modal fade" id="tambah" tabindex="-1" role="dialog" aria-labelledby="tambahLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="tambahLabel">Tambah Barang</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="{{route('product.store')}}" method="post" enctype="multipart/form-data">
        @csrf
      <div class="modal-body">
        <label>Kategori</label>
        <div class="form-group">
          <select class="form-control" name="catid">
            <option selected> Pilih Kategori </option>
            @foreach($category as $cat)
            <option value="{{$cat->id}}">{{$cat->nama_category}}</option>
            @endforeach
          </select>
        </div>
        <label>Nama Produk</label>
        <div class="form-group">
        	<input type="text" class="form-control" placeholder="nama Produk" name="namaproduk">
        </div>
        <label>Deskripsi</label>
        <div class="form-group">
        	<input type="text" class="form-control" placeholder="Deskripsi Produk" name="deskproduk">
        </div>
        <label>Harga Produk</label>
        <div class="form-group">
        	<input type="text" class="form-control" placeholder="Rp. ......." name="hargaproduk">
        </div>
        <label>Stok</label>
        <div class="form-group">
        	<input type="text" class="form-control" placeholder="Jumlah Stok" name="stok">
        </div>
        <div class="form-group">
          <label>Upload Gambar</label>
          <div class="input-group">
            <div class="custom-file">
              <input type="file" class="custom-file-input" id="inputGroupFile04" name="fotproduk" required>
              <label class="custom-file-label" for="inputGroupFile04">Pilih file</label>
            </div>
          </div>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">batal</button>
        <button type="submit" class="btn btn-primary">Tambah</button>
      </div>
      </form>
    </div>
  </div>
</div>


@push('addon-script')

    <script type="text/javascript">
        $(document).ready(function() {
          $('#bootstrap-data-table-export').DataTable();
      } );
  </script>
<script>
// Add the following code if you want the name of the file appear on select
$(".custom-file-input").on("change", function() {
  var fileName = $(this).val().split("\\").pop();
  $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});
</script>
@endpush

resources/views/seller/page/transaksi.blade.php
@extends('seller.layouts.app')

@section('title','Transaksi')

@section('content')


<div class="animated fadeIn">
    <div class="row">
    	<h4>Data Transaksi</h4>
    	<hr>
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                </div>
                <div class="card-body">
                    <table id="bootstrap-data-table" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                            	<th>No</th>
                                <th>Invoice</th>
                                <th>Nama Penerima</th>
                                <th>tanggal</th>
                                <th>Produk</th>
                                <th>Qty</th>
                                <th>Total</th>
                                <th>Status</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($trans as $data)
                            <tr>
                            	<td>{{$loop->iteration}}</td>
                                <td>{{$data->invoice}}</td>
                                <td>{{$data->nama_penerima}}</td>
                                <td>{{$data->created_at}}</td>
                                <td>{{$data->nama_produk}}</td>
                                <td>{{$data->qty}}</td>
                                <td>{{$data->total}}</td>
                                <td>
                                @if($data->status == 0)
                                    <p class="badge badge-warning">Menunggu</p>
                                @elseif($data->status == 1)
                                    <p class="badge badge-info">Diproses</p>
                                @elseif($data->status == 2 )
                                    <p class="badge badge-secondary">Dikirim</p>
                                @elseif($data->status == 3)
                                    <p class="badge badge-success">Selesai</p>
                                @else
                                    <p class="badge badge-danger">Batal</p>
                                @endif
                                </td>
                                <td>
                                	<a href="{{route('transaksi.edit',$data->id)}}" class="btn btn-sm btn-secondary"><i class="fa fa-edit"></i> ubah Status</a>
                                </td>
                            </tr>
                           @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>


    </div>
</div>

@endsection

@push('addon-script')

    <script type="text/javascript">
        $(document).ready(function() {
          $('#bootstrap-data-table-export').DataTable();
      } );
  </script>

@endpush

resources/views/seller/page/ubahstatus.blade.php
@extends('seller.layouts.app')

@section('title','Ubah Status')

@section('content')


@push('addon-style')
<style>
  .file {
  visibility: hidden;
  position: absolute;
}
</style>

<div class="animated fadeIn">
    <div class="row">
    	<h4>Ubah Produk</h4>
    	<hr>
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                   
                </div>
                <div class="card-body">
                   <label>Invoice</label>
                  <div class="form-group">
                    <input type="text" class="form-control text-primary" value="{{$data->invoice}}" disabled>
                  </div>
                   <label>Nama Penerima</label>
                  <div class="form-group">
                    <input type="text" class="form-control text-primary" value="{{$data->nama_penerima}}" disabled>
                  </div>
                   <label>Tanggal</label>
                  <div class="form-group">
                    <input type="text" class="form-control text-primary" value="{{$data->created_at}}" disabled>
                  </div>
                   <label>Produk</label>
                  <div class="form-group">
                    <input type="text" class="form-control text-primary" value="{{$data->nama_produk}}" disabled>
                  </div>
                    <form action="{{route('transaksi.update',$data->id)}}" method="post">
                    @csrf
                    @method('put')
                   <label>Qty</label>
                  <div class="form-group">
                    <input type="hidden" name="stok" value="{{$data->stok}}">
                    <input type="text" class="form-control text-primary" value="{{$data->qty}}" name="quantity" disabled>
                  </div>
                   <label>Total</label>
                  <div class="form-group">
                    <input type="text" class="form-control text-primary" value="{{$data->total}}" disabled>
                  </div>
                  <label>Bukti Bayar</label>
                  <div class="form-group">
                    <img style="max-width: 200px;" src="{{asset('/')}}{{$data->bukti_bayar}}">
                  </div>
                    
                    <label>Status</label>
                    <div class="form-group">
                      <select class="form-control" name="status">
                        <option value="0">Menunggu</option>
                        <option value="1" @if($data->status == 1 ) selected @endif>Diproses</option>
                        <option value="2" @if($data->status == 2 ) selected @endif>Dikirim</option>
                        <option value="3" @if($data->status == 3 ) selected @endif>Selesai</option>
                        <option value="4" @if($data->status == 4 ) selected @endif>Batal</option>
                      </select>
                    </div>
                  </div>
                  <div class="card-footer">
                    <button type="submit" class="btn btn-secondary float-right"> Simpan</button>
                  </div>
                </form>
            </div>
        </div>


    </div>
</div>

@endsection

@push('addon-script')
<script>
// Add the following code if you want the name of the file appear on select
$(".custom-file-input").on("change", function() {
  var fileName = $(this).val().split("\\").pop();
  $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});
</script>

<script>
  $(document).on("click", ".browse", function() {
  var file = $(this).parents().find(".file");
  file.trigger("click");
});
$('input[type="file"]').change(function(e) {
  var fileName = e.target.files[0].name;
  $("#file").val(fileName);

  var reader = new FileReader();
  reader.onload = function(e) {
    // get loaded data and render thumbnail.
    document.getElementById("preview").src = e.target.result;
  };
  // read the image file as a data URL.
  reader.readAsDataURL(this.files[0]);
});
</script>
@endpush